### ISSUE TITLE
[thruway-0.4] Misleading configuration names

### ISSUE THREAD

**Issue by mtancoigne** [WyriHaximus/Ratchet#52]
https://github.com/WyriHaximus/Ratchet/blob/thruway-0.4/config/config.sample.php#L6
The config state:
```php
            'internal' => [
                'address' => '0.0.0.0',
                'port' => 12345,
            ],
            'external' => [
                'hostname' => '127.0.0.1',
                'port' => 80,
            ],
```
The weird thing is I was able to conenct to the instance on port 80 (from another server) with this configuration:

```php
            'internal' => [
                'address' => '0.0.0.0',
                'port' => 80,
            ],
            'external' => [
                'hostname' => 'my.host.dev',
                'port' => 12345,
            ],
```

I have "Connection refused" errors in other cases.

**Comment by WyriHaximus** [comment]
I'll add clarification to that file and documentation. But in short `internal` the address and port the process listens on, while `external` is what is exposed to the users end. These options are in there because on the box it self you might listen on `0.0.0.0:1234` while externally you connect through nginx or another reverse proxy at `site.tld:80`.
