### ISSUE TITLE
Message Broad casting slow

### ISSUE THREAD

**Issue by chandrakant-bachhav** [WyriHaximus/Ratchet#54]
Hello,
I have configure this ratchet in my cakephp 3 web services for gaming purpose, it working fine at last month but now it broadcasting message slowly in multiple users.
Currently It's working fine for 5 connection on one socket, but whenever 7 to 10 users connect then it's broadcasting is too slow.

Thanks

**Comment by WyriHaximus** [comment]
To get an idea about what is going on:
* Are the clients constantly connected, and when there isn't anything to do a heartbeat is send to keep the connection alive?
* How do you store data?
* How do you broadcast?
* How do you know the broadcast is slow? (How do you measure it?)

Reason I'm asking a bunch of questions is because that low user count shouldn't be an issue at all. Above 250 I've been people run into issues due to architectural decisions. But it should be able to handle several thousand connections without breaking a sweat.
